
id: nyc_taxi_s3
namespace: zoomcamp

inputs:
  - id: taxi
    type: SELECT
    values: ["yellow", "green"]
    defaults: "yellow"
  - id: year
    type: SELECT
    values: ["2019", "2020", "2021"]
    defaults: "2020"
  - id: month
    type: SELECT
    values: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]
    defaults: "01"

tasks:
  - id: download_csv
    type: io.kestra.plugin.core.http.Download
    # Esta versión asegura que use la fecha del trigger si existe, o los inputs si es manual
    uri: "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/{{render(taxi ?? inputs.taxi)}}/{{render(taxi ?? inputs.taxi)}}_tripdata_{{trigger.date | date('yyyy-MM') ?? inputs.year ~ '-' ~ inputs.month}}.csv.gz"

  - id: upload_to_s3
    type: io.kestra.plugin.aws.s3.Upload
    accessKeyId: "YOUR_AWS_ACCESS_KEY_ID"
    secretKeyId: "YOUR_AWS_SECRET_ACCESS_KEY"
    region: "us-east-1"
    bucket: "dez-james-taxi-data-2026"
    key: "raw/{{render(taxi ?? inputs.taxi)}}/{{trigger.date | date('yyyy/MM') ?? inputs.year ~ '/' ~ inputs.month}}/data.csv.gz"
    from: "{{ outputs.download_csv.uri }}"

triggers:
  - id: daily
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 * * *"